"""Changed name of foreign key status to status_id

Revision ID: 04c85ed6dcbd
Revises: b58688ed7e3e
Create Date: 2024-10-13 16:32:15.151805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c85ed6dcbd'
down_revision: Union[str, None] = 'b58688ed7e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_status_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user_statuses', ['status_id'], ['id'])
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_status_fkey', 'users', 'user_statuses', ['status'], ['id'])
    op.drop_column('users', 'status_id')
    op.drop_table('email_codes')
    # ### end Alembic commands ###
