"""Change name of token in sweatscore_users table to session_token

Revision ID: 7ec0cde5b91f
Revises: ed01c5d725da
Create Date: 2024-10-22 22:38:50.088978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec0cde5b91f'
down_revision: Union[str, None] = 'ed01c5d725da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(length=200), nullable=True))
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
