"""Add created_at field to email_codes

Revision ID: 8fd5412b1c9e
Revises: 04c85ed6dcbd
Create Date: 2024-10-13 23:54:35.327858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd5412b1c9e'
down_revision: Union[str, None] = '04c85ed6dcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_codes', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_codes', 'created_at')
    # ### end Alembic commands ###
